export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO ='AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR ='AGREGAR_USUARIO_ERROR';

export const LISTADO_USUARIOS = 'LISTADO_USUARIOS';
export const LISTADO_USUARIOS_EXITO = 'LISTADO_USUARIOS_EXITO';
export const LISTADO_USUARIOS_ERROR = 'LISTADO_USUARIOS_ERROR';

export const OBTENER_USUARIO_ELIMINAR = 'OBTENER_USUARIO_ELIMINAR';
export const USUARIO_ELIMINAR_EXITO = 'USUARIO_ELIMINAR_EXITO';
export const USUARIO_ELIMINAR_ERROR = 'USUARIO_ELIMINAR_ERROR';

export const OBTENER_USUARIO_EDITAR = 'OBTENER_USUARIO_EDITAR';
export const COMENZAR_EDICION_USUARIO= 'COMENZAR_EDICION_USUARIO';
export const USUARIO_EDITADO_EXITO = 'USUARIO_EDITADO_EXITO';
export const USUARIO_EDITADO_ERROR = 'USUARIO_EDITADO_ERROR';

